### PR TITLE
Sarak edits 20190530

### PR DESCRIPTION
**Pull request by SKuebbing**

### CODE REVIEW

**Comment by seananderson** [comment]
Thanks! Can you send me something on the new references you added? Even if you just paste the basic metadata (authors, titles, year) here, I can look them up.

**Comment by seananderson** [comment]
Because these edits were on an older fork, there were too many conflicts with more recent edits to automatically merge them in. I added them by hand [here](https://github.com/seananderson/ecology-trends/commit/7c47f0d070ec2e1608a9c7d08a6a8f39fc7cffda). Some are still in comments and I will integrate them later. I'll also add the metadata for your references when you send it.

For any future edits, make sure to start a new branch here on the main repository. Don't work on your fork... that's a more advanced collaboration model that will probably be confusing. You would also have to keep it up-to-date with this main fork. (I realize you ended up with the fork because you tried contributing before you had permissions to start a branch.)

Thanks for the edits!

**Comment by SKuebbing** [comment]
Sean, 

Sorry!! New to GitHub and messing things up! How do I tell if I'm on the correct master branch or not?

Here are refs...metadata and also PDFs attached.

Brooker RW, FT Maestre, RM Callaway, CL Lortie, LA Cavieres, G Kunstler, P Liancourt, K Tielbörger, JMJ Travis, F Anthelme, C Armas, L Coll, C Corcket, S Delzon, E Forey, Z Kikvidze, J Olofsson, F Pugnaire, CL Quiroz, P SAccone, K Schiffers, M Seifan, B Touzard, R Michalet. Facilitation in plant communities: the past, the present, and the future. Journal of Ecology.

Bruno JF, JJ Stachowicz, MD Bertness. 2003. Inclusion of facilitation into ecological theory. Trends in Ecology and Evolution.

Díaz S, J Settelem, E Brondízio + IPBES Expert authors. 2019. Summary for policymakers of the global assessment report on biodiversity and ecosystem services of the Intergovernmental Science-Policy plantform on Biodiversity and Ecosystem Services. (Advanced Unedited Version) [sorry, I don't know the best way to cite this: here's the link..https://www.ipbes.net/global-assessment-biodiversity-ecosystem-services

Edgerton FN. 1983. The history of ecology: achievements and opportunities, part one. Journal of the History of Biology.

Farman JC, BG Gardiner, JD Shanklin. 1985. Large losses of total ozone in Antarctica reveal seasonal ClOx/NOx interaction. Nature

Griffiths RA, M Dos Santos. 2012. Trends in conservation biology: progress or procrastination in a new millennium? Biological Conservation.

Huston MA, AM Ellison, D Frank, ST Jackson, X Jiang, M Lau, JA Lockwood, SD Prager, DS Reiners, WA Reiners, E Schulze, JH Vandermeer, PA Werner. 2016. External influences on ecological theory: report on organized oral session 80 at the 100th anniversary meeting of the Ecological Society of America.  The Bulletin of the Ecological Society of America

Li J, MH Wang, YS Ho. 2011. Trends in research on global climate change: A Science Citation Index Expanded-based analysis. Global and Planetary Change.

Margles SW, RB Peterson, J Ervin, BA Kaplin. Conservation without borders: building communication and action across disciplinary boundaries for effective conservation. Environmental Management.

Millennium Ecosystem Assessment. 2005. Ecosystems and Human well-being: synthesis. Island Press, Washington, DC.

Simberloff D. 1980. A succession of paradigms in ecology: essentialism to materialism and probabilism. Synthese.

Staples TL, JM Dwyer, CE Wainwright, MM Mayfield. 2019. Applied ecological research is on the rise but connectivity barriers persist between four major subfields. Journal of Applied Ecology.

Tansley AG. 1935. The use and abuse of vegetational concepts and terms. Ecology.

Willis AJ. 1997. The Ecosystem: an evolving concept viewed historically. Functional Ecology

Young TP, DA Petersen, JJ Clay. 2005. The ecology of restoration: historical links, emerging issues and unexplored realms. Ecology Letters

**Comment by SKuebbing** [comment]
oh, and here are pdfs if that's helpful [got them - thanks!]

**Comment by SKuebbing** [comment]
And, a few more cites I forgot in the list (books, so I don't have the PDFs)

Kingsland, SE. 2005. The evolution of American ecology, 1890-2000. Johns Hopkins University Press, Baltimore, USA. 328 pp

Lockwood JL, MF Hoopers, MP Marchetti. 2013. Invasion Ecology. Wilely-Blackwell, West Sussex UK. Second Edition. 444pp

Simberloff, D. 2011. Charles Elton: neither founder nor siren, but prophet. in Fifty Years of Invasion Ecology: The Legacy of Charles Elton. DM Richardson Ed. John Wiley & Sons, West Sussex, UK. 432pp.

**Comment by seananderson** [comment]
Thanks. I'll get those in there.

I just added some more details to the Wiki (there's a link at the top of the repository): https://github.com/seananderson/ecology-trends/wiki/Contributing-via-a-branch---pull-request

The short answer is that you want to look at the URL in your browser and make sure it has something like this:
`https://github.com/seananderson/ecology-trends`

The other one is your fork. You can delete that if you want or just ignore it. You will know you are on your fork if you see something like this at the top left:
image

If you are on the main repository (where you should be) it will look like this:
image

There are 'forks' and 'branches'. You shouldn't be doing anything with forks here. I was trying to avoid that to keep it simple. (Yes, I know, Git is never simple ;) ).

**Comment by SKuebbing** [comment]
Got it. THANKS!!

**Pull request closed without merging**
